FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends protobuf-compiler \
    && pip install --no-cache-dir pyzmq protobuf grpcio-tools \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /app

RUN python -m grpc_tools.protoc -I./contratos --python_out=./shared/protos ./contratos/contrato.proto

CMD ["python", "broker.py"]

