services:
  orquestrador:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: orquestrador
    command: ["python", "broker.py"]
    ports:
      - "5555:5555"
      - "5556:5556"

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: proxy
    command: ["python", "proxy.py"]
    ports:
      - "5557:5557"
      - "5558:5558"

  referencia:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: referencia
    command: ["python", "referencia.py"]
    ports:
      - "5559:5559"

  servidor_python:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: servidor_python
    command: ["python", "servidores/python/servidor.py"]
    environment:
      - ORQ_ENDPOINT_SERVIDOR=tcp://orquestrador:5556
      - PROXY_PUB_ENDPOINT=tcp://proxy:5557
      - REFERENCE_ENDPOINT=tcp://referencia:5559
      - SERVER_NAME=servidor_python
      - DATA_DIR=/data
    volumes:
      - ./dados/servidor_python:/data
    depends_on:
      - orquestrador
      - proxy
      - referencia

  cliente_python:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: cliente_python
    command: ["python", "clientes/python/cliente.py"]
    environment:
      - ORQ_ENDPOINT=tcp://orquestrador:5555
      - PROXY_SUB_ENDPOINT=tcp://proxy:5558
      - CLIENTE_NOME=cliente_python
      - CLIENTE_CANAL=canal_cliente_python
    depends_on:
      - orquestrador
      - proxy
   #   - servidor_python

  servidor_go:
    build:
      context: .
      dockerfile: Dockerfile.go
    container_name: servidor_go
    command: ["/servidor"]
    environment:
      - ORQ_ENDPOINT_SERVIDOR=tcp://orquestrador:5556
      - PROXY_PUB_ENDPOINT=tcp://proxy:5557
      - REFERENCE_ENDPOINT=tcp://referencia:5559
      - SERVER_NAME=servidor_go
      - DATA_DIR=/data
    volumes:
      - ./dados/servidor_go:/data
    depends_on:
      - orquestrador
      - proxy
      - referencia

  cliente_go:
    build:
      context: .
      dockerfile: Dockerfile.go
    container_name: cliente_go
    command: ["/cliente"]
    environment:
      - ORQ_ENDPOINT=tcp://orquestrador:5555
      - PROXY_SUB_ENDPOINT=tcp://proxy:5558
      - CLIENTE_NOME=cliente_go
      - CLIENTE_CANAL=canal_go
    depends_on:
      - orquestrador
      - proxy
      - servidor_go

  servidor_java:
    build:
      context: .
      dockerfile: Dockerfile.java
    container_name: servidor_java
    command: ["ServidorJava"]
    environment:
      - ORQ_ENDPOINT_SERVIDOR=tcp://orquestrador:5556
      - PROXY_PUB_ENDPOINT=tcp://proxy:5557
      - REFERENCE_ENDPOINT=tcp://referencia:5559
      - SERVER_NAME=servidor_java
      - DATA_DIR=/data
    volumes:
      - ./dados/servidor_java:/data
    depends_on:
      - orquestrador
      - proxy
      - referencia

  cliente_java:
    build:
      context: .
      dockerfile: Dockerfile.java
    container_name: cliente_java
    command: ["ClienteJava"]
    environment:
      - ORQ_ENDPOINT=tcp://orquestrador:5555
      - PROXY_SUB_ENDPOINT=tcp://proxy:5558
      - CLIENTE_NOME=cliente_java
      - CLIENTE_CANAL=canal_java
    depends_on:
      - orquestrador
      - proxy
      - servidor_java
  servidor_csharp:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.csharp
    container_name: servidor_csharp
    environment:
      - ORQ_ENDPOINT_SERVIDOR=tcp://orquestrador:5556
      - PROXY_PUB_ENDPOINT=tcp://proxy:5557
      - REFERENCE_ENDPOINT=tcp://referencia:5559
      - SERVER_NAME=servidor_csharp
      - DATA_DIR=/data
    volumes:
      - ./dados/servidor_csharp:/data
    depends_on:
      - orquestrador
      - proxy
      - referencia
      
  cliente_csharp:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.csharp
    container_name: cliente_csharp
    entrypoint: ["dotnet", "cliente/Cliente.dll"]
    environment:
      - ORQ_ENDPOINT=tcp://orquestrador:5555
      - PROXY_SUB_ENDPOINT=tcp://proxy:5558
      - CLIENTE_NOME=cliente_csharp
      - CLIENTE_CANAL=canal_csharp
    depends_on:
      - orquestrador
      - proxy
      - servidor_csharp
