// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: contrato.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_SUCESSO Status = 0
	Status_STATUS_ERRO    Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_SUCESSO",
		1: "STATUS_ERRO",
	}
	Status_value = map[string]int32{
		"STATUS_SUCESSO": 0,
		"STATUS_ERRO":    1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_contrato_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_contrato_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_contrato_proto_rawDescGZIP(), []int{0}
}

type Cabecalho struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IdTransacao     int32                  `protobuf:"varint,1,opt,name=id_transacao,json=idTransacao,proto3" json:"id_transacao,omitempty"`
	LinguagemOrigem string                 `protobuf:"bytes,2,opt,name=linguagem_origem,json=linguagemOrigem,proto3" json:"linguagem_origem,omitempty"`
	TimestampEnvio  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp_envio,json=timestampEnvio,proto3" json:"timestamp_envio,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Cabecalho) Reset() {
	*x = Cabecalho{}
	mi := &file_contrato_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cabecalho) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cabecalho) ProtoMessage() {}

func (x *Cabecalho) ProtoReflect() protoreflect.Message {
	mi := &file_contrato_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cabecalho.ProtoReflect.Descriptor instead.
func (*Cabecalho) Descriptor() ([]byte, []int) {
	return file_contrato_proto_rawDescGZIP(), []int{0}
}

func (x *Cabecalho) GetIdTransacao() int32 {
	if x != nil {
		return x.IdTransacao
	}
	return 0
}

func (x *Cabecalho) GetLinguagemOrigem() string {
	if x != nil {
		return x.LinguagemOrigem
	}
	return ""
}

func (x *Cabecalho) GetTimestampEnvio() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampEnvio
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cabecalho     *Cabecalho             `protobuf:"bytes,1,opt,name=cabecalho,proto3" json:"cabecalho,omitempty"`
	NomeUsuario   string                 `protobuf:"bytes,2,opt,name=nome_usuario,json=nomeUsuario,proto3" json:"nome_usuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_contrato_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contrato_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_contrato_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetCabecalho() *Cabecalho {
	if x != nil {
		return x.Cabecalho
	}
	return nil
}

func (x *LoginRequest) GetNomeUsuario() string {
	if x != nil {
		return x.NomeUsuario
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cabecalho     *Cabecalho             `protobuf:"bytes,1,opt,name=cabecalho,proto3" json:"cabecalho,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=chat.Status" json:"status,omitempty"` // SUCESSO ou ERRO
	ErroMsg       string                 `protobuf:"bytes,3,opt,name=erro_msg,json=erroMsg,proto3" json:"erro_msg,omitempty"`  // preenchido em caso de erro
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_contrato_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contrato_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_contrato_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetCabecalho() *Cabecalho {
	if x != nil {
		return x.Cabecalho
	}
	return nil
}

func (x *LoginResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_SUCESSO
}

func (x *LoginResponse) GetErroMsg() string {
	if x != nil {
		return x.ErroMsg
	}
	return ""
}

type CreateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cabecalho     *Cabecalho             `protobuf:"bytes,1,opt,name=cabecalho,proto3" json:"cabecalho,omitempty"`
	NomeCanal     string                 `protobuf:"bytes,2,opt,name=nome_canal,json=nomeCanal,proto3" json:"nome_canal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_contrato_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contrato_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_contrato_proto_rawDescGZIP(), []int{3}
}

func (x *CreateChannelRequest) GetCabecalho() *Cabecalho {
	if x != nil {
		return x.Cabecalho
	}
	return nil
}

func (x *CreateChannelRequest) GetNomeCanal() string {
	if x != nil {
		return x.NomeCanal
	}
	return ""
}

type CreateChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cabecalho     *Cabecalho             `protobuf:"bytes,1,opt,name=cabecalho,proto3" json:"cabecalho,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=chat.Status" json:"status,omitempty"`
	ErroMsg       string                 `protobuf:"bytes,3,opt,name=erro_msg,json=erroMsg,proto3" json:"erro_msg,omitempty"` // ex: "canal já existe", "nome inválido"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelResponse) Reset() {
	*x = CreateChannelResponse{}
	mi := &file_contrato_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelResponse) ProtoMessage() {}

func (x *CreateChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contrato_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelResponse.ProtoReflect.Descriptor instead.
func (*CreateChannelResponse) Descriptor() ([]byte, []int) {
	return file_contrato_proto_rawDescGZIP(), []int{4}
}

func (x *CreateChannelResponse) GetCabecalho() *Cabecalho {
	if x != nil {
		return x.Cabecalho
	}
	return nil
}

func (x *CreateChannelResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_SUCESSO
}

func (x *CreateChannelResponse) GetErroMsg() string {
	if x != nil {
		return x.ErroMsg
	}
	return ""
}

type ListChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cabecalho     *Cabecalho             `protobuf:"bytes,1,opt,name=cabecalho,proto3" json:"cabecalho,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset() {
	*x = ListChannelsRequest{}
	mi := &file_contrato_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsRequest) ProtoMessage() {}

func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contrato_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_contrato_proto_rawDescGZIP(), []int{5}
}

func (x *ListChannelsRequest) GetCabecalho() *Cabecalho {
	if x != nil {
		return x.Cabecalho
	}
	return nil
}

type ListChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cabecalho     *Cabecalho             `protobuf:"bytes,1,opt,name=cabecalho,proto3" json:"cabecalho,omitempty"`
	Canais        []string               `protobuf:"bytes,2,rep,name=canais,proto3" json:"canais,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset() {
	*x = ListChannelsResponse{}
	mi := &file_contrato_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResponse) ProtoMessage() {}

func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contrato_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_contrato_proto_rawDescGZIP(), []int{6}
}

func (x *ListChannelsResponse) GetCabecalho() *Cabecalho {
	if x != nil {
		return x.Cabecalho
	}
	return nil
}

func (x *ListChannelsResponse) GetCanais() []string {
	if x != nil {
		return x.Canais
	}
	return nil
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cabecalho     *Cabecalho             `protobuf:"bytes,1,opt,name=cabecalho,proto3" json:"cabecalho,omitempty"`
	Canal         string                 `protobuf:"bytes,2,opt,name=canal,proto3" json:"canal,omitempty"`
	Mensagem      string                 `protobuf:"bytes,3,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_contrato_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contrato_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_contrato_proto_rawDescGZIP(), []int{7}
}

func (x *PublishRequest) GetCabecalho() *Cabecalho {
	if x != nil {
		return x.Cabecalho
	}
	return nil
}

func (x *PublishRequest) GetCanal() string {
	if x != nil {
		return x.Canal
	}
	return ""
}

func (x *PublishRequest) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cabecalho     *Cabecalho             `protobuf:"bytes,1,opt,name=cabecalho,proto3" json:"cabecalho,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=chat.Status" json:"status,omitempty"`
	ErroMsg       string                 `protobuf:"bytes,3,opt,name=erro_msg,json=erroMsg,proto3" json:"erro_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_contrato_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contrato_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_contrato_proto_rawDescGZIP(), []int{8}
}

func (x *PublishResponse) GetCabecalho() *Cabecalho {
	if x != nil {
		return x.Cabecalho
	}
	return nil
}

func (x *PublishResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_SUCESSO
}

func (x *PublishResponse) GetErroMsg() string {
	if x != nil {
		return x.ErroMsg
	}
	return ""
}

type ChannelMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Canal          string                 `protobuf:"bytes,1,opt,name=canal,proto3" json:"canal,omitempty"`
	Mensagem       string                 `protobuf:"bytes,2,opt,name=mensagem,proto3" json:"mensagem,omitempty"`
	Remetente      string                 `protobuf:"bytes,3,opt,name=remetente,proto3" json:"remetente,omitempty"`
	TimestampEnvio *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp_envio,json=timestampEnvio,proto3" json:"timestamp_envio,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChannelMessage) Reset() {
	*x = ChannelMessage{}
	mi := &file_contrato_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessage) ProtoMessage() {}

func (x *ChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_contrato_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessage.ProtoReflect.Descriptor instead.
func (*ChannelMessage) Descriptor() ([]byte, []int) {
	return file_contrato_proto_rawDescGZIP(), []int{9}
}

func (x *ChannelMessage) GetCanal() string {
	if x != nil {
		return x.Canal
	}
	return ""
}

func (x *ChannelMessage) GetMensagem() string {
	if x != nil {
		return x.Mensagem
	}
	return ""
}

func (x *ChannelMessage) GetRemetente() string {
	if x != nil {
		return x.Remetente
	}
	return ""
}

func (x *ChannelMessage) GetTimestampEnvio() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampEnvio
	}
	return nil
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cabeçalho comum a todas as mensagens.
	Cabecalho *Cabecalho `protobuf:"bytes,1,opt,name=cabecalho,proto3" json:"cabecalho,omitempty"`
	// oneof garante que apenas UM desses campos esteja presente por mensagem.
	//
	// Types that are valid to be assigned to Conteudo:
	//
	//	*Envelope_LoginReq
	//	*Envelope_LoginRes
	//	*Envelope_CreateChannelReq
	//	*Envelope_CreateChannelRes
	//	*Envelope_ListChannelsReq
	//	*Envelope_ListChannelsRes
	//	*Envelope_PublishReq
	//	*Envelope_PublishRes
	Conteudo      isEnvelope_Conteudo `protobuf_oneof:"conteudo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_contrato_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_contrato_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_contrato_proto_rawDescGZIP(), []int{10}
}

func (x *Envelope) GetCabecalho() *Cabecalho {
	if x != nil {
		return x.Cabecalho
	}
	return nil
}

func (x *Envelope) GetConteudo() isEnvelope_Conteudo {
	if x != nil {
		return x.Conteudo
	}
	return nil
}

func (x *Envelope) GetLoginReq() *LoginRequest {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_LoginReq); ok {
			return x.LoginReq
		}
	}
	return nil
}

func (x *Envelope) GetLoginRes() *LoginResponse {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_LoginRes); ok {
			return x.LoginRes
		}
	}
	return nil
}

func (x *Envelope) GetCreateChannelReq() *CreateChannelRequest {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_CreateChannelReq); ok {
			return x.CreateChannelReq
		}
	}
	return nil
}

func (x *Envelope) GetCreateChannelRes() *CreateChannelResponse {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_CreateChannelRes); ok {
			return x.CreateChannelRes
		}
	}
	return nil
}

func (x *Envelope) GetListChannelsReq() *ListChannelsRequest {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_ListChannelsReq); ok {
			return x.ListChannelsReq
		}
	}
	return nil
}

func (x *Envelope) GetListChannelsRes() *ListChannelsResponse {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_ListChannelsRes); ok {
			return x.ListChannelsRes
		}
	}
	return nil
}

func (x *Envelope) GetPublishReq() *PublishRequest {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_PublishReq); ok {
			return x.PublishReq
		}
	}
	return nil
}

func (x *Envelope) GetPublishRes() *PublishResponse {
	if x != nil {
		if x, ok := x.Conteudo.(*Envelope_PublishRes); ok {
			return x.PublishRes
		}
	}
	return nil
}

type isEnvelope_Conteudo interface {
	isEnvelope_Conteudo()
}

type Envelope_LoginReq struct {
	// Login
	LoginReq *LoginRequest `protobuf:"bytes,2,opt,name=login_req,json=loginReq,proto3,oneof"`
}

type Envelope_LoginRes struct {
	LoginRes *LoginResponse `protobuf:"bytes,3,opt,name=login_res,json=loginRes,proto3,oneof"`
}

type Envelope_CreateChannelReq struct {
	// Criação de canal
	CreateChannelReq *CreateChannelRequest `protobuf:"bytes,4,opt,name=create_channel_req,json=createChannelReq,proto3,oneof"`
}

type Envelope_CreateChannelRes struct {
	CreateChannelRes *CreateChannelResponse `protobuf:"bytes,5,opt,name=create_channel_res,json=createChannelRes,proto3,oneof"`
}

type Envelope_ListChannelsReq struct {
	// Listagem de canais
	ListChannelsReq *ListChannelsRequest `protobuf:"bytes,6,opt,name=list_channels_req,json=listChannelsReq,proto3,oneof"`
}

type Envelope_ListChannelsRes struct {
	ListChannelsRes *ListChannelsResponse `protobuf:"bytes,7,opt,name=list_channels_res,json=listChannelsRes,proto3,oneof"`
}

type Envelope_PublishReq struct {
	// Publicacao
	PublishReq *PublishRequest `protobuf:"bytes,8,opt,name=publish_req,json=publishReq,proto3,oneof"`
}

type Envelope_PublishRes struct {
	PublishRes *PublishResponse `protobuf:"bytes,9,opt,name=publish_res,json=publishRes,proto3,oneof"`
}

func (*Envelope_LoginReq) isEnvelope_Conteudo() {}

func (*Envelope_LoginRes) isEnvelope_Conteudo() {}

func (*Envelope_CreateChannelReq) isEnvelope_Conteudo() {}

func (*Envelope_CreateChannelRes) isEnvelope_Conteudo() {}

func (*Envelope_ListChannelsReq) isEnvelope_Conteudo() {}

func (*Envelope_ListChannelsRes) isEnvelope_Conteudo() {}

func (*Envelope_PublishReq) isEnvelope_Conteudo() {}

func (*Envelope_PublishRes) isEnvelope_Conteudo() {}

var File_contrato_proto protoreflect.FileDescriptor

const file_contrato_proto_rawDesc = "" +
	"\n" +
	"\x0econtrato.proto\x12\x04chat\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x01\n" +
	"\tCabecalho\x12!\n" +
	"\fid_transacao\x18\x01 \x01(\x05R\vidTransacao\x12)\n" +
	"\x10linguagem_origem\x18\x02 \x01(\tR\x0flinguagemOrigem\x12C\n" +
	"\x0ftimestamp_envio\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampEnvio\"`\n" +
	"\fLoginRequest\x12-\n" +
	"\tcabecalho\x18\x01 \x01(\v2\x0f.chat.CabecalhoR\tcabecalho\x12!\n" +
	"\fnome_usuario\x18\x02 \x01(\tR\vnomeUsuario\"\x7f\n" +
	"\rLoginResponse\x12-\n" +
	"\tcabecalho\x18\x01 \x01(\v2\x0f.chat.CabecalhoR\tcabecalho\x12$\n" +
	"\x06status\x18\x02 \x01(\x0e2\f.chat.StatusR\x06status\x12\x19\n" +
	"\berro_msg\x18\x03 \x01(\tR\aerroMsg\"d\n" +
	"\x14CreateChannelRequest\x12-\n" +
	"\tcabecalho\x18\x01 \x01(\v2\x0f.chat.CabecalhoR\tcabecalho\x12\x1d\n" +
	"\n" +
	"nome_canal\x18\x02 \x01(\tR\tnomeCanal\"\x87\x01\n" +
	"\x15CreateChannelResponse\x12-\n" +
	"\tcabecalho\x18\x01 \x01(\v2\x0f.chat.CabecalhoR\tcabecalho\x12$\n" +
	"\x06status\x18\x02 \x01(\x0e2\f.chat.StatusR\x06status\x12\x19\n" +
	"\berro_msg\x18\x03 \x01(\tR\aerroMsg\"D\n" +
	"\x13ListChannelsRequest\x12-\n" +
	"\tcabecalho\x18\x01 \x01(\v2\x0f.chat.CabecalhoR\tcabecalho\"]\n" +
	"\x14ListChannelsResponse\x12-\n" +
	"\tcabecalho\x18\x01 \x01(\v2\x0f.chat.CabecalhoR\tcabecalho\x12\x16\n" +
	"\x06canais\x18\x02 \x03(\tR\x06canais\"q\n" +
	"\x0ePublishRequest\x12-\n" +
	"\tcabecalho\x18\x01 \x01(\v2\x0f.chat.CabecalhoR\tcabecalho\x12\x14\n" +
	"\x05canal\x18\x02 \x01(\tR\x05canal\x12\x1a\n" +
	"\bmensagem\x18\x03 \x01(\tR\bmensagem\"\x81\x01\n" +
	"\x0fPublishResponse\x12-\n" +
	"\tcabecalho\x18\x01 \x01(\v2\x0f.chat.CabecalhoR\tcabecalho\x12$\n" +
	"\x06status\x18\x02 \x01(\x0e2\f.chat.StatusR\x06status\x12\x19\n" +
	"\berro_msg\x18\x03 \x01(\tR\aerroMsg\"\xa5\x01\n" +
	"\x0eChannelMessage\x12\x14\n" +
	"\x05canal\x18\x01 \x01(\tR\x05canal\x12\x1a\n" +
	"\bmensagem\x18\x02 \x01(\tR\bmensagem\x12\x1c\n" +
	"\tremetente\x18\x03 \x01(\tR\tremetente\x12C\n" +
	"\x0ftimestamp_envio\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampEnvio\"\xcb\x04\n" +
	"\bEnvelope\x12-\n" +
	"\tcabecalho\x18\x01 \x01(\v2\x0f.chat.CabecalhoR\tcabecalho\x121\n" +
	"\tlogin_req\x18\x02 \x01(\v2\x12.chat.LoginRequestH\x00R\bloginReq\x122\n" +
	"\tlogin_res\x18\x03 \x01(\v2\x13.chat.LoginResponseH\x00R\bloginRes\x12J\n" +
	"\x12create_channel_req\x18\x04 \x01(\v2\x1a.chat.CreateChannelRequestH\x00R\x10createChannelReq\x12K\n" +
	"\x12create_channel_res\x18\x05 \x01(\v2\x1b.chat.CreateChannelResponseH\x00R\x10createChannelRes\x12G\n" +
	"\x11list_channels_req\x18\x06 \x01(\v2\x19.chat.ListChannelsRequestH\x00R\x0flistChannelsReq\x12H\n" +
	"\x11list_channels_res\x18\a \x01(\v2\x1a.chat.ListChannelsResponseH\x00R\x0flistChannelsRes\x127\n" +
	"\vpublish_req\x18\b \x01(\v2\x14.chat.PublishRequestH\x00R\n" +
	"publishReq\x128\n" +
	"\vpublish_res\x18\t \x01(\v2\x15.chat.PublishResponseH\x00R\n" +
	"publishResB\n" +
	"\n" +
	"\bconteudo*-\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_SUCESSO\x10\x00\x12\x0f\n" +
	"\vSTATUS_ERRO\x10\x01B%Z#projeto-mensageria/shared/go/protosb\x06proto3"

var (
	file_contrato_proto_rawDescOnce sync.Once
	file_contrato_proto_rawDescData []byte
)

func file_contrato_proto_rawDescGZIP() []byte {
	file_contrato_proto_rawDescOnce.Do(func() {
		file_contrato_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contrato_proto_rawDesc), len(file_contrato_proto_rawDesc)))
	})
	return file_contrato_proto_rawDescData
}

var file_contrato_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contrato_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_contrato_proto_goTypes = []any{
	(Status)(0),                   // 0: chat.Status
	(*Cabecalho)(nil),             // 1: chat.Cabecalho
	(*LoginRequest)(nil),          // 2: chat.LoginRequest
	(*LoginResponse)(nil),         // 3: chat.LoginResponse
	(*CreateChannelRequest)(nil),  // 4: chat.CreateChannelRequest
	(*CreateChannelResponse)(nil), // 5: chat.CreateChannelResponse
	(*ListChannelsRequest)(nil),   // 6: chat.ListChannelsRequest
	(*ListChannelsResponse)(nil),  // 7: chat.ListChannelsResponse
	(*PublishRequest)(nil),        // 8: chat.PublishRequest
	(*PublishResponse)(nil),       // 9: chat.PublishResponse
	(*ChannelMessage)(nil),        // 10: chat.ChannelMessage
	(*Envelope)(nil),              // 11: chat.Envelope
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_contrato_proto_depIdxs = []int32{
	12, // 0: chat.Cabecalho.timestamp_envio:type_name -> google.protobuf.Timestamp
	1,  // 1: chat.LoginRequest.cabecalho:type_name -> chat.Cabecalho
	1,  // 2: chat.LoginResponse.cabecalho:type_name -> chat.Cabecalho
	0,  // 3: chat.LoginResponse.status:type_name -> chat.Status
	1,  // 4: chat.CreateChannelRequest.cabecalho:type_name -> chat.Cabecalho
	1,  // 5: chat.CreateChannelResponse.cabecalho:type_name -> chat.Cabecalho
	0,  // 6: chat.CreateChannelResponse.status:type_name -> chat.Status
	1,  // 7: chat.ListChannelsRequest.cabecalho:type_name -> chat.Cabecalho
	1,  // 8: chat.ListChannelsResponse.cabecalho:type_name -> chat.Cabecalho
	1,  // 9: chat.PublishRequest.cabecalho:type_name -> chat.Cabecalho
	1,  // 10: chat.PublishResponse.cabecalho:type_name -> chat.Cabecalho
	0,  // 11: chat.PublishResponse.status:type_name -> chat.Status
	12, // 12: chat.ChannelMessage.timestamp_envio:type_name -> google.protobuf.Timestamp
	1,  // 13: chat.Envelope.cabecalho:type_name -> chat.Cabecalho
	2,  // 14: chat.Envelope.login_req:type_name -> chat.LoginRequest
	3,  // 15: chat.Envelope.login_res:type_name -> chat.LoginResponse
	4,  // 16: chat.Envelope.create_channel_req:type_name -> chat.CreateChannelRequest
	5,  // 17: chat.Envelope.create_channel_res:type_name -> chat.CreateChannelResponse
	6,  // 18: chat.Envelope.list_channels_req:type_name -> chat.ListChannelsRequest
	7,  // 19: chat.Envelope.list_channels_res:type_name -> chat.ListChannelsResponse
	8,  // 20: chat.Envelope.publish_req:type_name -> chat.PublishRequest
	9,  // 21: chat.Envelope.publish_res:type_name -> chat.PublishResponse
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_contrato_proto_init() }
func file_contrato_proto_init() {
	if File_contrato_proto != nil {
		return
	}
	file_contrato_proto_msgTypes[10].OneofWrappers = []any{
		(*Envelope_LoginReq)(nil),
		(*Envelope_LoginRes)(nil),
		(*Envelope_CreateChannelReq)(nil),
		(*Envelope_CreateChannelRes)(nil),
		(*Envelope_ListChannelsReq)(nil),
		(*Envelope_ListChannelsRes)(nil),
		(*Envelope_PublishReq)(nil),
		(*Envelope_PublishRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contrato_proto_rawDesc), len(file_contrato_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contrato_proto_goTypes,
		DependencyIndexes: file_contrato_proto_depIdxs,
		EnumInfos:         file_contrato_proto_enumTypes,
		MessageInfos:      file_contrato_proto_msgTypes,
	}.Build()
	File_contrato_proto = out.File
	file_contrato_proto_goTypes = nil
	file_contrato_proto_depIdxs = nil
}
